{# string  -------------------------------------------------     #}

{%- macro type_max_string() -%}
        {{ return(adapter.dispatch('type_max_string', 'snowplow_utils')()) }}
{%- endmacro -%}

{% macro default__type_max_string() %}
    {{ dbt.type_string() }}
{% endmacro %}
{# Redshift is the only warehouse that does not have a max length string generated by default (256 chars instead) #}
{% macro redshift__type_max_string() %}
    varchar(max)
{% endmacro %}
