name: 'snowplow_utils'
version: '0.17.4'
config-version: 2

require-dbt-version: [">=1.4.0", "<2.0.0"]

profile: 'default'

dispatch:
  - macro_namespace: dbt
    search_order: ['snowplow_utils', 'dbt']

macro-paths: ["macros"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "dbt_packages"

vars:
    surrogate_key_treat_nulls_as_empty_strings: true #turn on legacy behavior
